### ISSUE TITLE
Button style messed up by parent page stylesheet

### ISSUE THREAD

**Issue by tnajdek** [zotero/publications#39] opened 2016-06-07 11:45 UTC
Because we're overriding some of the styles and inherit others, when embedded on other pages, button might appear with broken styling. Caused by #35 

<img width="640" alt="screen shot 2016-06-07 at 13 42 54" src="https://cloud.githubusercontent.com/assets/214628/15856503/103bc6a0-2cb6-11e6-9922-4bb99bd5498f.png">

**Comment by johanneskrtek** [comment] 2016-06-07 13:39
Can't reproduce. What happens – bolder font-weight, text-shadow, larger margin-top (how can this be, is the larger spacing part of the reference above?)?

Font-weight and text-shadow should be fixed by now.

**Closed** 2016-06-08 20:01 UTC
